name: serena_onlus_login
description: Applicazione di login per pagina web

publish_to: 'Serema Onlus'


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  path_provider: ^2.0.11
  http: ^0.13.5
  flutter_downloader: ^1.8.4
  permission_handler: ^10.2.0
  flutter_inappwebview: ^5.7.1
  url_launcher: ^6.1.6
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - s.jpg
  uses-material-design: true
